name: Portfolio
on: [push]
jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: build project
        run: npm run build
      - name: setup finished
        run: echo project bulid successfull

